### ISSUE TITLE
i can't run viabackwards on my bungeecord server

### ISSUE THREAD

**Issue by polarcn** [Matsv/ViaBackwards#18]
### What is the output url of /viaversion dump?
> 08:58:14 [警告] Exception encountered when loading plugin: ViaBackwards
java.lang.ExceptionInInitializerError
    at nl.matsv.viabackwards.api.ViaBackwardsPlatform.init(ViaBackwardsPlatform.java:32)
    at nl.matsv.viabackwards.BungeePlugin.onEnable(BungeePlugin.java:20)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:226)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:274)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: java.lang.NullPointerException
    at us.myles.ViaVersion.api.protocol.ProtocolRegistry.registerProtocol(ProtocolRegistry.java:68)
    at us.myles.ViaVersion.api.protocol.ProtocolRegistry.<clinit>(ProtocolRegistry.java:32)
    ... 6 more

### How/when does this error happen? login?:
> when i run the Bungeecord

### Is there an error in the console? Use pastebin.com. Is there a kick message?:
> 08:58:14 [警告] Exception encountered when loading plugin: ViaBackwards
java.lang.ExceptionInInitializerError
    at nl.matsv.viabackwards.api.ViaBackwardsPlatform.init(ViaBackwardsPlatform.java:32)
    at nl.matsv.viabackwards.BungeePlugin.onEnable(BungeePlugin.java:20)
    at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:226)
    at net.md_5.bungee.BungeeCord.start(BungeeCord.java:274)
    at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:55)
    at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: java.lang.NullPointerException
    at us.myles.ViaVersion.api.protocol.ProtocolRegistry.registerProtocol(ProtocolRegistry.java:68)
    at us.myles.ViaVersion.api.protocol.ProtocolRegistry.<clinit>(ProtocolRegistry.java:32)
    ... 6 more
no

**Comment by Matsv** [comment]
Could you give me the output of /ViaVersion dump?

**Comment by Matsv** [comment]
Closing because you didn't respond. Please provide more info to reopen the issue.
